### ISSUE TITLE
変数の宣言が必要

### ISSUE THREAD

**Issue by kamataryo** [yukaiguchi/kadai#1]
ここは、 `let result` ではなく、 `let result = 0` として、最初に 0 を入れておかないと計算ができません。

https://github.com/yukaiguchi/kadai/blob/309339f3fcbb66e00cc1181a62d0fa622c2fcf23/kadai-4/index.js#L11

実行結果は以下のようになっているはずです。
```javascript
sum(500) // NaN
```

`NaN` とは Not a Number のことで、計算が失敗している状態です。
プログラムは一度自分で実行して、結果を確認するようにすると理解が深まると思います。

**Comment by yukaiguchi** [comment]
井口ゆかです。ご指摘ありがとうございます。
確認不足でした。これからは気をつけたいと思います。

2020年2月9日(日) 13:56 Kamata Ryo <notifications@github.com>:
